import {
  FIRST_IRRF_ALIQUOT,
  SECOND_IRRF_ALIQUOT,
  THIRD_IRRF_ALIQUOT,
  FOURTH_IRRF_ALIQUOT,
  FIFTH_IRRF_ALIQUOT,
  FIRST_IRRF_DEDUCTION,
  SECOND_IRRF_DEDUCTION,
  THIRD_IRRF_DEDUCTION,
  FOURTH_IRRF_DEDUCTION,
  FIFTH_IRRF_DEDUCTION,
} from '../constants';

const irrfValuesTable = {
  firstIrrfValues: [FIRST_IRRF_ALIQUOT, FIRST_IRRF_DEDUCTION],
  secondtIrrfValues: [SECOND_IRRF_ALIQUOT, SECOND_IRRF_DEDUCTION],
  thirdIrrfValues: [THIRD_IRRF_ALIQUOT, THIRD_IRRF_DEDUCTION],
  fourthIrrfValues: [FOURTH_IRRF_ALIQUOT, FOURTH_IRRF_DEDUCTION],
  fifthIrrfValues: [FIFTH_IRRF_ALIQUOT, FIFTH_IRRF_DEDUCTION],
};

export default irrfValuesTable;
