import {
  FIRST_ALIQUOT,
  SECOND_ALIQUOT,
  THIRD_ALIQUOT,
  FOURTH_ALIQUOT,
  FIFTH_ALIQUOT,
  FIRST_IRRF_DEDUCTION,
  SECOND_IRRF_DEDUCTION,
  THIRD_IRRF_DEDUCTION,
  FOURTH_IRRF_DEDUCTION,
  FIFTH_IRRF_DEDUCTION,
} from '../constants/irrf';

const irrfValuesTable = {
  firstIrrfValues: [FIRST_ALIQUOT, FIRST_IRRF_DEDUCTION],
  secondtIrrfValues: [SECOND_ALIQUOT, SECOND_IRRF_DEDUCTION],
  thirdIrrfValues: [THIRD_ALIQUOT, THIRD_IRRF_DEDUCTION],
  fourthIrrfValues: [FOURTH_ALIQUOT, FOURTH_IRRF_DEDUCTION],
  fifthIrrfValues: [FIFTH_ALIQUOT, FIFTH_IRRF_DEDUCTION],
};

export default irrfValuesTable;
