const FIRST_INSS_RANGE_VALUE = 1212;
const SECOND_INSS_RANGE_VALUE = 2427.35;
const THIRD_INSS_RANGE_VALUE = 3641.03;
const FOURTH_INSS_RANGE_VALUE = 7087.22;

const FIRST_ALIQUOT = 0.075;
const SECOND_ALIQUOT = 0.09;
const THIRD_ALIQUOT = 0.12;
const FOURTH_ALIQUOT = 0.14;

const FIRST_INSS_DEDUCTION = 0;
const SECOND_INSS_DEDUCTION = 18.18;
const THIRD_INSS_DEDUCTION = 91;
const FOURTH_INSS_DEDUCTION = 163.82;

const INSS_TETO_DEDUCTION = 828.39;

module.exports = {
  FIRST_INSS_RANGE_VALUE,
  SECOND_INSS_RANGE_VALUE,
  THIRD_INSS_RANGE_VALUE,
  FOURTH_INSS_RANGE_VALUE,
  FIRST_ALIQUOT,
  SECOND_ALIQUOT,
  THIRD_ALIQUOT,
  FOURTH_ALIQUOT,
  FIRST_INSS_DEDUCTION,
  SECOND_INSS_DEDUCTION,
  THIRD_INSS_DEDUCTION,
  FOURTH_INSS_DEDUCTION,
  INSS_TETO_DEDUCTION,
};
