const FIRST_IRRF_RANGE_VALUE = 1903.98;
const SECOND_IRRF_RANGE_VALUE = 2826.65;
const THIRD_IRRF_RANGE_VALUE = 3751.05;
const FOURTH_IRRF_RANGE_VALUE = 4664.68;

const FIRST_ALIQUOT = 0;
const SECOND_ALIQUOT = 0.075;
const THIRD_ALIQUOT = 0.15;
const FOURTH_ALIQUOT = 0.225;
const FIFTH_ALIQUOT = 0.275;

const FIRST_IRRF_DEDUCTION = 0;
const SECOND_IRRF_DEDUCTION = 142.8;
const THIRD_IRRF_DEDUCTION = 354.8;
const FOURTH_IRRF_DEDUCTION = 636.13;
const FIFTH_IRRF_DEDUCTION = 869.36;

module.exports = {
  FIRST_IRRF_RANGE_VALUE,
  SECOND_IRRF_RANGE_VALUE,
  THIRD_IRRF_RANGE_VALUE,
  FOURTH_IRRF_RANGE_VALUE,
  FIRST_ALIQUOT,
  SECOND_ALIQUOT,
  THIRD_ALIQUOT,
  FOURTH_ALIQUOT,
  FIFTH_ALIQUOT,
  FIRST_IRRF_DEDUCTION,
  SECOND_IRRF_DEDUCTION,
  THIRD_IRRF_DEDUCTION,
  FOURTH_IRRF_DEDUCTION,
  FIFTH_IRRF_DEDUCTION,
};
